[package]
name = "mxtransform"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
color-eyre = "0.6.3"
image = "0.25.5"
indicatif = "0.17.11"
ndarray = "0.16.1"
